begin;

create or replace function private.normalize_ingredient_name(p_name text)
returns text
language sql
immutable
set search_path = ''
as $$
  select trim(
    regexp_replace(
      regexp_replace(
        translate(
          lower(trim(coalesce(p_name,''))),
          'áàäâãåéèëêíìïîóòöôõúùüûñç',
          'aaaaaaeeeeiiiiooooouuuunc'
        ),
        '[^a-z0-9]+',
        ' ',
        'g'
      ),
      '\s+',
      ' ',
      'g'
    )
  );
$$;

create table if not exists public.ingredient_aliases (
  id bigint generated by default as identity primary key,
  alias_text text not null,
  normalized_alias text not null unique,
  ingredient_id uuid not null references public.ingredients(id) on delete cascade,
  created_at timestamptz not null default now()
);

alter table public.ingredient_aliases enable row level security;
revoke all on table public.ingredient_aliases from anon, authenticated;

create temp table ingredient_merge_map (
  source_name text primary key,
  target_name text not null
) on commit drop;

insert into ingredient_merge_map(source_name,target_name) values
  ('aguacate','palta'),
  ('palta/aguacate','palta'),
  ('papa/patata','papa'),
  ('papa rallada','papa'),
  ('puré de papa','papa'),
  ('zucchini/calabacín','zucchini'),
  ('choclo','maíz'),
  ('maíz/choclo','maíz'),
  ('batata/boniato','batata'),
  ('boniato','batata'),
  ('crema/nata','crema de leche'),
  ('ciboulette picado','cebolla de verdeo'),
  ('cebollín','cebolla de verdeo'),
  ('cebollino','cebolla de verdeo'),
  ('harina de trigo común','harina común'),
  ('zumo de limón','jugo de limón'),
  ('mozzarella rallada','queso mozzarella'),
  ('queso mozzarella rallado','queso mozzarella'),
  ('queso mozzarella light','queso mozzarella'),
  ('queso parmesano rallado','queso parmesano'),
  ('sésamo','semillas de sésamo'),
  ('semillas de sésamo blanco','semillas de sésamo'),
  ('huevo cocido','huevo'),
  ('huevos batidos','huevo'),
  ('zanahoria rallada','zanahoria'),
  ('cilantro fresco','cilantro'),
  ('perejil fresco','perejil'),
  ('orégano seco','orégano'),
  ('eneldo fresco','eneldo'),
  ('eneldo seco','eneldo'),
  ('espinaca fresca','espinaca'),
  ('espinaca congelada','espinaca'),
  ('masa de hojaldre fresca','masa de hojaldre'),
  ('masa de hojaldre rectangular','masa de hojaldre'),
  ('carne picada magra','carne picada'),
  ('pollo a la plancha','pollo'),
  ('pollo hervido y desmechado','pollo'),
  ('pechuga de pollo','pollo'),
  ('atún al natural escurrido','atún'),
  ('arroz cocido','arroz'),
  ('hojas de lechuga','lechuga'),
  ('yogur griego natural sin azúcar','yogur griego'),
  ('queso crema light','queso crema'),
  ('queso rallado light','queso rallado'),
  ('pimienta negra','pimienta'),
  ('pesto de albahaca','pesto'),
  ('pesto vegano de albahaca','pesto'),
  ('aceite de oliva virgen extra','aceite de oliva'),
  ('salsa sriracha','sriracha'),
  ('tortillas de harina','tortillas/wraps'),
  ('Rapiditas de Chía & Lino','tortillas/wraps'),
  ('condimentos favoritos','condimentos');

insert into public.ingredients(canonical_name,normalized_name)
select distinct m.target_name, private.normalize_ingredient_name(m.target_name)
from ingredient_merge_map m
where not exists (
  select 1
  from public.ingredients i
  where private.normalize_ingredient_name(i.canonical_name)=private.normalize_ingredient_name(m.target_name)
)
on conflict (normalized_name) do nothing;

insert into public.ingredient_aliases(alias_text,normalized_alias,ingredient_id)
select m.source_name,
       private.normalize_ingredient_name(m.source_name),
       target.id
from ingredient_merge_map m
join public.ingredients target
  on private.normalize_ingredient_name(target.canonical_name)=private.normalize_ingredient_name(m.target_name)
on conflict (normalized_alias)
do update set ingredient_id=excluded.ingredient_id, alias_text=excluded.alias_text;

update public.recipe_ingredients ri
set ingredient_id=target.id
from ingredient_merge_map m
join public.ingredients source
  on private.normalize_ingredient_name(source.canonical_name)=private.normalize_ingredient_name(m.source_name)
join public.ingredients target
  on private.normalize_ingredient_name(target.canonical_name)=private.normalize_ingredient_name(m.target_name)
where ri.ingredient_id=source.id
  and source.id<>target.id;

delete from public.ingredients source
using ingredient_merge_map m
where private.normalize_ingredient_name(source.canonical_name)=private.normalize_ingredient_name(m.source_name)
  and not exists (
    select 1 from public.recipe_ingredients ri where ri.ingredient_id=source.id
  )
  and private.normalize_ingredient_name(m.source_name)<>private.normalize_ingredient_name(m.target_name);

update public.ingredients
set normalized_name=private.normalize_ingredient_name(canonical_name)
where normalized_name is distinct from private.normalize_ingredient_name(canonical_name);

insert into public.ingredient_aliases(alias_text,normalized_alias,ingredient_id)
select i.canonical_name,private.normalize_ingredient_name(i.canonical_name),i.id
from public.ingredients i
on conflict (normalized_alias)
do update set ingredient_id=excluded.ingredient_id, alias_text=excluded.alias_text;

with extra_raw(alias_text,target_name) as (
 values
  ('patata','papa'),
  ('patatas','papa'),
  ('papas','papa'),
  ('aguacate','palta'),
  ('aguacates','palta'),
  ('paltas','palta'),
  ('calabacín','zucchini'),
  ('calabacin','zucchini'),
  ('calabacines','zucchini'),
  ('zucchinis','zucchini'),
  ('choclo','maíz'),
  ('choclos','maíz'),
  ('maiz','maíz'),
  ('boniato','batata'),
  ('boniatos','batata'),
  ('batatas','batata'),
  ('nata','crema de leche'),
  ('ciboulette','cebolla de verdeo'),
  ('cebollín','cebolla de verdeo'),
  ('cebollino','cebolla de verdeo'),
  ('cebolla verde','cebolla de verdeo'),
  ('mozzarella','queso mozzarella'),
  ('parmesano','queso parmesano'),
  ('sésamo','semillas de sésamo'),
  ('sesamo','semillas de sésamo'),
  ('huevos','huevo'),
  ('tomates cherry','tomate cherry'),
  ('sriracha sauce','sriracha')
),
extra as (
 select distinct on (private.normalize_ingredient_name(alias_text))
        alias_text,target_name
 from extra_raw
 order by private.normalize_ingredient_name(alias_text),alias_text
)
insert into public.ingredient_aliases(alias_text,normalized_alias,ingredient_id)
select e.alias_text,
       private.normalize_ingredient_name(e.alias_text),
       target.id
from extra e
join public.ingredients target
  on private.normalize_ingredient_name(target.canonical_name)=private.normalize_ingredient_name(e.target_name)
on conflict (normalized_alias)
do update set ingredient_id=excluded.ingredient_id, alias_text=excluded.alias_text;

create or replace function private.canonicalize_ingredient_insert()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_norm text;
  v_target public.ingredients;
begin
  v_norm:=private.normalize_ingredient_name(coalesce(new.canonical_name,new.normalized_name));

  select i.*
  into v_target
  from public.ingredient_aliases a
  join public.ingredients i on i.id=a.ingredient_id
  where a.normalized_alias=v_norm
  limit 1;

  if found then
    new.canonical_name:=v_target.canonical_name;
    new.normalized_name:=v_target.normalized_name;
  else
    new.canonical_name:=trim(new.canonical_name);
    new.normalized_name:=v_norm;
  end if;

  return new;
end;
$$;

drop trigger if exists ingredients_canonicalize_before_insert on public.ingredients;
create trigger ingredients_canonicalize_before_insert
before insert on public.ingredients
for each row execute function private.canonicalize_ingredient_insert();

commit;